# Generated by Django 4.1.6 on 2023-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping_for_himself', '0002_brand_modeltitle_price_size_title_remove_offer_zice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
