# Generated by Django 4.1.6 on 2023-02-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoping_for_himself', '0003_alter_title_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltitle',
            name='title',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='model',
        ),
        migrations.AddField(
            model_name='title',
            name='model',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoping_for_himself.modeltitle'),
        ),
        migrations.AlterField(
            model_name='price',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
